### ISSUE TITLE
Шаблонный erase для ассоциативных контейнеров

### ISSUE THREAD

**Issue by Neargye** [cpp-ru/ideas#119]
_Перенос предложения:_ голоса +2, -2
_Автор идеи:_ **Yaroslav Shchukin**

условный `std::set::contains` добавили , а про `template<class K> iterator erase(const K& x)` забыли

`template<class K> iterator erase(const K& x)` добавить, чтобы` std::less<>` использовать

**Comment by Neargye** [comment]
**maxon 13 августа 2019, 20:08**
А можно пример? Где именно здесь должен быть использован другой less<>? 
Также непонятно, что тут за K. Если K приводимо к key_type, то неясно зачем шаблон. Если неприводимо, то вообще неясно что этот метод должен делать.

**Comment by apolukhin** [comment]
Речь идёт про добавление гетерогенного erase в контейнеры, чтобы иметь возможность удалять из контейнера по ключу другого типа.

Например, чтобы из `std::set<std::string> v;` можно было удалить элемент через `v.erase("A long key to remove from container")` без создания std::string и динамической аллокации

**Comment by apolukhin** [comment]
Ребята из Интела написали предложение https://wg21.link/p2077 . Молодцы!

**Comment by apolukhin** [comment]
Ребята из Интела продолжают жечь https://wg21.link/p2363 - добавляют оставшиеся недостающие гетерогенные перегрузки

**Comment by apolukhin** [comment]
https://wg21.link/p2077 приняли в C++23
