### ISSUE TITLE
C++ switch выражения

### ISSUE THREAD

**Issue by Neargye** [cpp-ru/ideas#152]
_Перенос предложения:_ голоса +16, -6
_Автор идеи:_ **Игорь Шаповал**

В С++ имеется switch statement. Во многих языках имеется также switch expression. Выражения позволяет возращать с switch значения, в ветке указывать несколько значений, а также отсутствует проблема с fallthrough.

Для сравнения для того чтобы возратить значения с switch statement нужно написать.
```cpp
int numLetters;
switch (day) {
    case MONDAY:
    case FRIDAY:
    case SUNDAY:
        numLetters = 6;
        break;
    case TUESDAY:
        numLetters = 7;
        break;
    case THURSDAY:
    case SATURDAY:
        numLetters = 8;
        break;
    case WEDNESDAY:
        numLetters = 9;
        break;
    default:
        throw new IllegalStateException("Wat: " + day);
}
```
А чтобы возратить значения с switch expression.
```cpp
int numLetters = switch (day) {
    case MONDAY, FRIDAY, SUNDAY -> 6;
    case TUESDAY                -> 7;
    case THURSDAY, SATURDAY     -> 8;
    case WEDNESDAY              -> 9;
};
```
Также обе формы полезны в дальнейшем продвижении pattern matching в язык С++.

**Comment by Neargye** [comment]
**Sasha Sitnikov 27 мая 2019, 15:39*
Pattern matching уже предложили

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1371r0.pdf


**Игорь Шаповал 27 мая 2019, 15:56**
В предложении хотят добавить паттерны через inspect. Предлагаю добавить отдельно к switch statement также switch expression.


**Maxim Kapitonov 30 октября 2019, 11:19**
а зачем : на -> менять?

**Comment by apolukhin** [comment]
Дубликат #239
