### ISSUE TITLE
Ограничение набора типов variadic pack'a

### ISSUE THREAD

**Issue by Neargye** [cpp-ru/ideas#155]
_Перенос предложения:_ голоса +2, -0
_Автор идеи:_ **Antervis**

Очень простой пример, демонстрирующий проблему: допустим, нам нужно что-то вроде функции, принимающей variadic pack int'ов:
```cpp
void foo(int... args) {
Реализовать такую функцию можно двумя способами, через requires/концепты:

template <Same<int> ...Args>
void foo(Args... args) {
либо через static_cast:

void foo(auto ...args) {
    __foo_impl(static_cast<int>(args)...);
}
```
Первый вариант не поддерживает неявные преобразования, т.е. требует явно приводить типы передаваемых аргументов. Второй вариант отключает возможность перегружать foo другими variadic версиями.

 

Идея: ввести возможность ограничения списка типов, принимаемых variadic pack'ом:
```cpp
void foo(auto ...(int) args);
```
Функция будет участвовать в перегрузке если все её аргументы могут быть неявно приведены к одному из перечисленных в ограничителе типам. Например, так можно будет объявить функцию объединения строк с преаллокацией:
```cpp
template <typename ...(std::string_view, Same<char>) Args>
auto join(Args args) {
// или
auto join(auto ...(std::string_view, Same<char>) args) {
// принимает типы, приводящиеся к string_view или удовлетворяющие концепту Same<char>
```
Также это позволит удобно реализовывать перегрузки variadic-pack функций

**Comment by Neargye** [comment]
**Andrey 30 мая 2019, 22:42**
http://wg21.link/p1219


**Antervis 31 мая 2019, 16:09**
Andrey, предлагаемое мной решение более универсальное


**Andrey 31 мая 2019, 22:04**
Antervis, я с первой попытки не понял, что именно Вы предлагаете, думал, что Вы хотите, чтобы в функцию парамерты приходили уже фиксированного типа. Но тогда это выражается как
```cpp
void foo(ConvertibleTo<int> auto...);
```
и соответственно 
```cpp
template<typename... Args>
  requires((ConvertibleTo<string_view> || Same<char>) && ...)
auto join(Args...);
```

**Comment by apolukhin** [comment]
Как верно заметили выше, работает с C++20 https://godbolt.org/z/PvdarP5ja
