### ISSUE TITLE
Краткая форма тела метода

### ISSUE THREAD

**Issue by Neargye** [cpp-ru/ideas#157]
_Перенос предложения:_ голоса +3, -10
_Автор идеи:_ **Игорь Шаповал**

В некоторых языках позволено записывать тело методы в краткой форме. 
```cpp
int length(const std::string& s) {
    return s.size();
}
```
Вместо традиционой формы, можно писать вот так.
```cpp
int length(const std::string& s) = s.size();
```
Также можно будет лаконично писать методы с switch expression.
```cpp
int day_of_week(int day) = switch (day) {
    case MONDAY, FRIDAY, SUNDAY -> 6;
    case TUESDAY                -> 7;
    case THURSDAY, SATURDAY     -> 8;
    case WEDNESDAY              -> 9;
};
```
Было б классно иметь такую форму записи методов и в С++ языке.

**Comment by Neargye** [comment]
**Sasha Sitnikov 27 мая 2019, 15:44**
```cpp
int length(const std::string& s) = s.size();
```
В таком виде не получится, ибо неоднозначность возникает с pure virtual methods:
```
class Class {
  virtual int foo() = 0;
};
```cpp

**Sasha Sitnikov 27 мая 2019, 15:51**
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0573r2.html

Здесь предлагается использовать =>
```cpp
[](auto&& a, auto&& b) { return a.id() < b.id(); } // C++14
[](a, b) => a.id() < b.id()                        // this proposal
```

**Игорь Шаповал 27 мая 2019, 16:00**
В каком состоянии [p0573r2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0573r2.html)? Есть ли какие-то сздвижения для включения в С++23?


**Andrey 27 мая 2019, 23:04**
Игорь Шаповал, https://www.reddit.com/r/cpp/comments/bcowjq/status_of_p0573/?utm_medium=android_app&utm_source=share

**Comment by apolukhin** [comment]
Международный комитет рассмотрел идею, идея не понравилась
