### ISSUE TITLE
Интерполяция строк

### ISSUE THREAD

**Issue by Neargye** [cpp-ru/ideas#272]
_Перенос предложения:_ голоса +7, -13
_Автор идеи:_ **Дмитрий Бравиков**

В C++ не хватает удобного типобезопасного способа подстановки переменных в шаблонную строку. Можно добавить интерполяцию строк, как в C#.

Пример кода:
```cpp
const char* name = "Bob";
int age = 32;
std::cout << $"Hello. My name is {name}. I'm {age}." << std::endl;
```
В стандартный вывод передается строка: `"Hello. My name is Bob. I'm 32."`.

Сейчас символ доллара `$` не используется в языке.

**Comment by Neargye** [comment]
**Дмитрий Бравиков 8 мая 2019, 14:24**
stringstream не может заменить шаблоны строк, когда нужна интернационализация.


**Alexander 8 мая 2019, 17:29**
Уже можно делать такие вещи при помощи <format>, который завезли в C++20.


**Дмитрий Бравиков 8 мая 2019, 18:47*
Alexander, Вы об этом Text Formatting? Это дает типобезопасность, но не дает интерполяции.



**Alexander 17 мая 2019, 7:31**
Дмитрий Бравиков, посмотрел ещё раз, что такое интерполяция. И не понял, зачем оно нужно в C++


**Владимир Топунов 19 июля 2019, 19:14**
Прикрутить рефлексию с перебором объявленных переменных. Полезно будет. Я за фичу, но только в library


**Maxim Kapitonov 30 октября 2019, 13:48**
Владимир Топунов, это не рефлексия.

Я так понимаю выражение на этапе компиляции должно развернуться в 

std::cout << "Hello. My name is" << name << ". I'm" << age << "." << std::endl;

**yndx-antoshkka 20 июля 2020, 20:20**
У Зверовича были идеи реализовать подобное, но оно требует рефлексии, которую ещё не приняли

**Comment by apolukhin** [comment]
Аналогичное предложение #87
