### ISSUE TITLE
Гарантировать размер объекта в агрегации

### ISSUE THREAD

**Issue by Neargye** [cpp-ru/ideas#273]
_Перенос предложения:_ голоса +1, -2
_Автор идеи:_ **_NN_**

Допустим мы имеем простую обёртку над указателем.

template<typename T>
struct ptr
{
 T* p;
};
Компилятор вправе добавить выравнивание по его усмотрению

template<typename T>
struct ptr
{
 T* p;
 // padding
};
В случае использования этого типа в класса, компилятор вправе добавить выравнивание также и самого класса:

class X
{
 ptr<int> p; 
 // внутреннее выравнивание ptr<int>
 // выравнивание для поля p
};
Получатся, что использование указателя меньше влияет на размер класса чем использование обёртки вокруг него.

Предложение:

Атрибут указывающий не добавлять лишнего выравнивания для таких классов таким образом гарантирующей легковестность любой обёртки то бишь array, unique_ptr и т.п.

template<typename T>
struct ptr [[raw_size]]
{
 T* p;
 // guaranteed no padding is added
};

**Comment by Neargye** [comment]
Дубликат https://github.com/cpp-ru/ideas/issues/199

**Comment by apolukhin** [comment]
Другая похожая идея #248
