### ISSUE TITLE
Добавление в стандарт возможности расширения типов

### ISSUE THREAD

**Issue by Neargye** [cpp-ru/ideas#274]
_Перенос предложения:_ голоса +5, -10
_Автор идеи:_ **Darkpaladin2000**

Немного кода:
```cpp
class SomeClass {
    int _a, int _b;
};

extension SomeClass {
public:
    int sumOfFields() {
        return _a + _b;
    }
};

//main
SomeClass object;
auto res = object.sumOfFields();
```
Расширения позволят добавлять функциональность в классы стандартной библиотеки без наследования.

Но будут ограничения на изменение существующей функциональности:
1. Нельзя менять реализацию существующих методов и операторов
2. Расширение не имеет своих конструкторов и деструктора, следовательно не имеет своих свойств.
3. Из расширяемого класса нельзя вызывать методы расширения

Расширения (extensions) используются в Swift.

**Comment by Neargye** [comment]
**Игорь Шаповал 1 мая 2019, 13:57**
Это похоже на partial class в С#. Было б классно если добавили.


**Alexey Kreschuk 4 мая 2019, 0:43**
В приведённом примере ломается изоляция: новый код может получить доступ к приватным членам класса. Если это починить, становится непонятно, зачем добавлять классу новые методы? Чем они лучше свободных функций?


**Дмитрий 6 мая 2019, 21:51**
Хотелось бы увидеть сценарии, где подобное усложнение языка необходимо или оправдано. На мой взгляд в некоторых случаях "расширение" типов может усложнить разбор кода.


**Айдар Фаттахов 14 мая 2019, 14:44**
В сишарпе нет свободных функций

У нас есть, поэтому чтобы сделать расширение foo.bar() нужно стандартизировать uniform call syntax bar(foo) а не вот этот вот костыль

**Comment by apolukhin** [comment]
Аналогичная идея с другим синтаксисом #30
