### ISSUE TITLE
Вывод std::chrono с точностью до наносекунд

### ISSUE THREAD

**Issue by Neargye** [cpp-ru/ideas#33]
_Перенос предложения:_ голоса +6, -0
_Автор идеи:_ **_NN_**

Решается сегодня через стороннюю библиотеку, хотя должно быть частью стандарта.

https://github.com/HowardHinnant/date/blob/master/include/date/date.h

```cpp
#include <iostream>
#include <string>

using namespace std;

template <class Precision>
string getISOCurrentTimestamp()
{
    auto now = chrono::system_clock::now();
    return date::format("%FT%TZ", date::floor<Precision>(now));
}

int main() {

 cout << getISOCurrentTimestamp<chrono::nanoseconds>();   
}
```

**Comment by apolukhin** [comment]
Участники РГ21 запросили повышение проритета задачи во время международного собрания и нам удалось убедить других участников в важности фичи. 

Идея по добавлению форматтеров для chrono стала частью C++20 http://eel.is/c++draft/time#format . Отдельное спасибо авторам https://wg21.link/p1361 за отличное предложение!
