### ISSUE TITLE
Конструктор для string_view, хранящий длину литерала

### ISSUE THREAD

**Issue by Neargye** [cpp-ru/ideas#34]
_Перенос предложения:_ голоса +1, -4
_Автор идеи:_ **Денис Черников**

В некоторых случаях мог бы быть полезен шаблонный конструктор std::string_view (с шаблонным параметром std::size_t N), принимающий массив CharT и инициализирующий длину контейнера равной шаблонному N.

P.S.: не проверял, будет ли это конфликтовать с текущими перегрузками конструктора.

**Comment by Neargye** [comment]
**Antervis12 января, 17:23**
а зачем? У вас если строковый литерал фиксированный, т.е. известен на этапе компиляции, значит и string_view от него, в котором будет содержаться размер, можно вычислить на этапе компиляции.

**Comment by apolukhin** [comment]
Современные компиляторы на этапе компиляции считают длину строки и инициализируют константным значением. constexpr на string_view тоже помогает, что позволяет теперь писать
`constexpr std::string_view kHello{"Hello"};` и иметь 100% гарантию на compile time инициализацию
