### ISSUE TITLE
хочу перегрузку оператора [] что бы как в питоне 

### ISSUE THREAD

**Issue by apolukhin** [cpp-ru/ideas#369]
_Перенос предложения:_ голоса +1, -11
_Автор идеи:_ **dreverser**

дать возможность перегружать оператор доступа к массиву []
что бы можно было использовать как в питоне [:-1] или [3:4] итд

вроде бы от асма ушли в высокоуровневые языки

а что то набирать букв приходиться еще больше для простых действий

как там смотрят в комиттете что бы определить перегрузку оператора []

в нестандартной перегрузке внутри двоеточие :

что бы можно было под него загнать много всяких алгоритмов и операций над массивами, строками, и куда вздумается

 

надеюсь все поняли о чем я, и питон цитировать сюда не буду

**Comment by apolukhin** [comment]
**yndx-antoshkka, 19 октября 2018, 13:29**
Есть немного похожее предложение: Несколько аргументов в перегруженном brackets operator #235

**Comment by apolukhin** [comment]
А оно должно работать только для массивов или и для контейнеров? А как реализовать для контейнеров?

**Comment by marakew** [comment]
это идея slice из питона
https://github.com/cpp-ru/ideas/issues/91
