### ISSUE TITLE
Оператор redirect вместо перегрузки точки

### ISSUE THREAD

**Issue by Neargye** [cpp-ru/ideas#37]
_Перенос предложения:_ голоса +0, -10
_Автор идеи:_ **Максим Некипелов**

Добавить оператор, который будет перенаправлять поле на другой объект, в случае если компилятор не нашел поля в данном объекте через оператор точки.

В некоторых ситуациях для удобства нужно перегрузить точку, но это выглядело бы очень странно и не понятно как работало.

Предлагаю добавить новый оператор redirect, который будет переадресовывать поле на другой объект, если компилятор его не нашел в действующем. Пример:
```cpp
#include <iostream>

struct Vector
{
    float X = 0.f;
};

template<class T>
struct Property
{
    T Get() const { { }; }

    redirect Get;
};

int main()
{
    Property<Vector> property;
    std::cout << property.X << std::endl; // поле X не было найдено внутри Property<Vector>, поэтому компилятор начинает его искать в Vector, если находит неявно преображает обращение в property.Get().X
}
 ```
На получение указателя поля:
```cpp
&Property<Vector>::X
```
Это распространяться не должно. Будет выдаваться ошибка.

**Comment by Neargye** [comment]
**Nikola_g11 декабря 2020, 18:55**
Мне кажется слишком запутано будет, если будет иерархия наследования или вложенность.

**Comment by apolukhin** [comment]
Фактически, это несколько другой синтаксис для "оператора точка". Мне подобный синтаксис нравится больше. Пенесу обсуждение в #100
