### ISSUE TITLE
std::vector<bool> problem

### ISSUE THREAD

**Issue by kirillgrachoff** [cpp-ru/ideas#440]
It is rude to write
```cpp
template <typename T>
auto& get_at(std::vector<T>& container, size_t index) {
    // write to log
    return container[index];
}
```
std::vector<bool>::operator[] returns _Bit_Reference which cannot be cast to bool& or const bool&

It is also rude to write
```cpp
T& value = container[index]
```
because of _Bit_Reference.

My suggestion is:
Rename `std::vector<bool>` to `std::dynamic_bitset` (or similar) to prevent compile-errors because of `std::vector<bool>` specialization.

**Comment by apolukhin** [comment]
Это поломает очень много кода, такая идея не пройдёт голосование
