### ISSUE TITLE
Отказ от с++

### ISSUE THREAD

**Issue by Vitalii-Shmidt** [cpp-ru/ideas#446]
предлагаю отказаться от с++ и запретить на нем писать, как-либо его пропагандировать. Удалить с++ из сети.

**Comment by apolukhin** [comment]
Тогда придётся отказаться от браузеров, игр, веб серверов, банковского ПО, медицинского оборудования, графических и видео редакторов, SpaceX и прочих космических программ, фондовых бирж, Андроида, C#, Java, Javascript, C, Rust...

... ведь всё это написано на C++
