### ISSUE TITLE
Добавить move-only  std::function 

### ISSUE THREAD

**Issue by raidenluikang** [cpp-ru/ideas#454]
_std::function не поддерживает move-only functors_

_std::function <int ()> f = [ m = std::make_unique<int>() ] (){ return *m; };   не компилируется_

_https://godbolt.org/z/hKhneEWz3_

```
template <typename R, typename ... Args >
class function < R(Args ... ) >
{
   // ....
    template <typename F>
     function ( F && f) ; // -->почему f  требуется чтобы она было копируемый? 
};
```

Полезные ссылки:
* https://godbolt.org/z/hKhneEWz3 - онлайн дизассемблер

**Comment by apolukhin** [comment]
Работ над идеей активно идет в https://wg21.link/p0288
Есть все шансы увидеть в C++23

**Comment by apolukhin** [comment]
В C++23 приняли https://wg21.link/p0288
