### ISSUE TITLE
Конструктор стандартных контейнеров от итераторов разного типа и Ranges

### ISSUE THREAD

**Issue by kirillgrachoff** [cpp-ru/ideas#458]
# Почему больно без этого
Возьмём код на С++. Вполне обычный код.
```cpp
std::vector<char> v;
// something useful
std::string s(v.begin(), v.end());
```
Работает.

Теперь вспомним про замечательные ***Ranges***.\
Что теперь хочется?\
А хочется вот так:
```cpp
std::string text = "this is simple text";
for (auto subs : std::ranges::split_view(text, ' ')) {
    // либо так:
    std::string word(std::ranges::begin(subs), std::ranges::end(subs));
    // либо так:
    std::string word(subs);
}
```

Но ни то, ни другое не компилируется т.к. у std::string (и у других контейнеров) нет таких штук.

# Предложение
Добавить к каждому std контейнеру **хотя бы** конструктор от двух итераторов разного типа (это несложно).
Всего лишь добавить
```cpp
template <typename InputIterFirst, typename InputIterLast>
requires Comparable<InputIterFirst, InputIterLast>
std::string(InputIterFirst first, InputIterLast last) {}
```
Где `Comparable<T, U>` - это `concept`, отвечающий за то, чтобы их можно было сравнивать друг с другом.

**Comment by AKonia** [comment]
А разве вот этот конструктор не тот, что вы ищете ?
```cpp
template< class InputIt >
basic_string( InputIt first, InputIt last, 
              const Allocator& alloc = Allocator() );
```
Да и разве это нормально, чтобы итераторы на основе которых вы создаёте строку имели разный тип, это чисто логически как ? Типо от элемента одного контейнера до элемента другого ? Подумайте, может чего-то просто не поняли и есть способ сделать то, что вы предлагаете по-другому

**Comment by kirillgrachoff** [comment]
Нет, это не тот конструктор.

`std::ranges::split_view` и другие **Ranges** могут иметь своим началом и концом итераторы разного типа. Самое главное, чтобы они были сравниваемы.
Попробуйте следующий код:
```cpp
std::string s = "hello world";
auto v = std::ranges::split_view(s, ' ');
for (auto i : v) {
    std::cout << std::is_same_v<decltype(std::ranges::begin(i)), decltype(std::ranges::end(i))> << '\n';
}
```

Как это логически: хочется за O(1) копировать `view`. Но хочется по нему итерироваться. Хочется за O(1) находить конец. Решение - сделать так, чтобы `end` возвращал другой тип, который бы дёргал объект и спрашивал, есть ли там следующий.

**Comment by tomilov** [comment]
Кажется предложения для sentinel-ов уже давно есть и что-то уже [есть](https://en.cppreference.com/w/cpp/experimental/ranges/iterator/Sentinel) в C++20 experimental. Наверняка и для контейнеров уже всё продумывается.

**Comment by tomilov** [comment]
Про конструирование контейнеров, которое затруднено на самом деле: https://timur.audio/how-to-make-a-container-from-a-c20-range

**Comment by apolukhin** [comment]
Комитет решил идти немного другим путём, через ranges::to https://wg21.link/p1206

**Comment by apolukhin** [comment]
Приняли в C++23 вместе с новыми конструкторами от диапазона для контейнеров https://wg21.link/p1206
