### ISSUE TITLE
Функции преобразования строки в число должны поддерживать работу с итераторами

### ISSUE THREAD

**Issue by Neargye** [cpp-ru/ideas#47]
_Перенос предложения:_ голоса +6, -0
_Автор идеи:_ **waka.packmaca**

Функции std::stoi, std::stol, std::stoll и т.д. принимают std::string/std::wstring в качестве аргумента, что делает их "бесполезными" при работе с диапазонами.

Хотелось бы иметь возможность помимо строк скармливать им пару итераторов, чтобы сигнатура функции имела следующий вид, например:
```cpp
template<typename Iterator>
int stoi(Iterator first, Iterator last, int base = 10) {
  // ...
}
```

**Comment by Neargye** [comment]
**m0xf2 декабря 2020, 21:28**
Для того, что не приходилось конструировать новую строку подошёл бы вариант stoi с аргументом типа string_view.  А у него уже есть конструктор от пары итераторов.

**develoit4 декабря 2020, 3:52**
m0xf, +

**Comment by apolukhin** [comment]
to_chars/from_chars в C++17 работают без создания std::string

std::stoi и аналоги улучшаются в #263
