### ISSUE TITLE
Float16 как builtin тип

### ISSUE THREAD

**Issue by ilnurkh** [cpp-ru/ideas#470]
_<Описание вашей идеи>_
Сделать поддержку этого типа в языке.
Отдельно стоит прописать неоднозначность операций. (можно поднимать до fp32 и после операции опускать назад, а можно так не делеть. Можно делать так для цепочки операций, а можно делать усечение после каждой). В общем сложностей много, надо начать с этим как-то работать.

_<Примеры, где ваша идея будет полезна. Чем больше примеров и чем большую аудиторию они охватывают - тем лучше>_
Весь нейроночный ml на нём. Пора уже и поддержать

_<Код c реализацией вашей идеи, если есть>_
https://github.com/catboost/catboost/tree/master/library/cpp/float16

Полезные ссылки:
* https://quick-bench.com/ - онлайн бенчмарк, поможет вам продемонстрировать эффективность вашего подхода
* https://godbolt.org/ - онлайн дизассемблер
* https://eel.is/c++draft/ - черновик стандарта C++ с возможностью ссылаться на конкретные параграфы
* https://wg21.link/ - универсальная ссылка на международные proposal или баги в С++, например https://wg21.link/P1000 ссылается на документ P1000, а https://wg21.link/cwg100 на 100 баг в ядре языка

**Comment by incoder1** [comment]
До С++ 98, по моему, в Borland C++ 3.1 был тип small как раз half repression 16 битный и математическим со-процессором поддерживался. В стандарте имеем только float, double и long double, как я понимаю потому как десктопные и серверные CPU и GPU в массе своей такой тип не поддерживают. Но вот мобильные GPU как раз поддерживают такой тип.

**Comment by ilnurkh** [comment]
сейчас почти всё кажется поддерживает уже
 cat /proc/cpuinfo | grep f16

**Comment by apolukhin** [comment]
Работа уже идёт https://wg21.link/p1467

**Comment by apolukhin** [comment]
Добавили std::float16_t и std::bfloat16_t

**Comment by ilnurkh** [comment]
в каком стандарте оно появится?
