### ISSUE TITLE
magic_get для структур

### ISSUE THREAD

**Issue by sergii-rybin-tfs** [cpp-ru/ideas#516]
Недавно в стандарт был добавлен structured binding.

По умолчанию, мы можем биндить поля структур без дополнительного кода.

Так же мы можем переопределить поведение по-умолчанию реализовав tuple-like интерфейс для класса или для структуры.

Досадно, что мы не можем воспользоваться tuple интерфейсом, который компилятор уже делает для нас. Предлагаю сделать  доступным автосгенерированный tuple интерфейс.

**Comment by apolukhin** [comment]
Идея уже в работе вот тут https://github.com/cpp-ru/ideas/issues/26
