### ISSUE TITLE
backport import std to C++20

### ISSUE THREAD

**Issue by kelbon** [cpp-ru/ideas#524]
В С++20 уже есть модули и import std использует обычный модуль без доработок из С++20, поэтому нет никаких препятствий использовать import std уже в С++20
Это позволит гораздо быстрее и легче переходить на модули старым проектам и конечно же ускорит компиляцию уже сейчас, а не через 5 лет

**Comment by apolukhin** [comment]
Все были против бекпортирования на уровне стандарта. Однако многие вендоры подтвердили, что реализуют модуль std в C++20 в качечтве расширения.
