### ISSUE TITLE
std::exclusive_or

### ISSUE THREAD

**Issue by dasfex** [cpp-ru/ideas#538]
В STL есть ```std::conjunction``` и ```std::disjunction```. Тут покрыты лишь две из трёх основных битовых операций в короткой форме. Однако нет никакого аналога xor-метафунктора (xor по определению не имеет короткой формы, но всё же). 

Possible implementation:
```cpp
template <typename T, typename... Args>
struct exclusive_or : exclusive_or<T, exclusive_or<Args...>> {};

template <typename T>
struct exclusive_or<T> : T {};

template <typename T, typename S>
struct exclusive_or<T, S> {
    static constexpr bool value = T::value ^ S::value;
};

template <typename... Args>
constexpr inline bool exclusive_or_v = exclusive_or<Args...>::value;
```

**Comment by tomilov** [comment]
Почему в определении бинарная операция а не логическая? Логическая - это `!=`.
Где требуется метафункция? Кроме консистентности есть какие-то другие причины, почему бы это нужно добавить в стандарт?
