### ISSUE TITLE
Форматирование в static_assert

### ISSUE THREAD

**Issue by Neargye** [cpp-ru/ideas#54]
_Перенос предложения:_ голоса +8, -2
_Автор идеи:_ **yehorror**

Добавить возможность выводить в static_assert не только строковое сообщение, но и какие-либо другие данные вместе с ним (известные на этапе компиляции): числа, bool, ну и т.д.

Как один из вариантов - сделать что-то вроде std::format.
```cpp
static_assert(sizeof(parameter) == sizeof(something), "Size of parameter must be {}", sizeof(something));
```

**Comment by Neargye** [comment]
**oficsu 20 июля 2020, 22:51**
Мне кажется, что достаточно снять требование на то, чтобы message был string literal и разрешить вторым аргументом передавать любой тип, способный в constexpr-контексте быть приведённым к char const*, в таком случае точно не произойдёт глупости и никто не смешает языковую и библиотечную фичу в кучу, каждый сможет написать свой форматтер, угодный его душе

Правда, возникают вопросы с зависимыми шаблонными параметрами. Так мы сможемdependent_false передать прямо в строку сообщения об ошибке, не уверен, есть ли связанные с этим проблемы

**Comment by apolukhin** [comment]
Приняли идею в C++26 в https://wg21.link/p2741
