### ISSUE TITLE
static_print

### ISSUE THREAD

**Issue by kov-serg** [cpp-ru/ideas#545]
Почему досих пор нет static_print? Уже 5 лет прошло.

https://github.com/saarraz/static-print

https://www.youtube.com/watch?v=61w4LbQ0fzU

**Comment by AndreyG** [comment]
Свежее предложение: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2758r0.html

**Comment by apolukhin** [comment]
Приняли в C++26 https://wg21.link/p2758
