### ISSUE TITLE
Получение файлового дескриптора из std::ofstream

### ISSUE THREAD

**Issue by gleb-kov** [cpp-ru/ideas#568]
_<Описание вашей идеи>_
Хочется добавить метод в std::ofstream который возвращает файловый дескриптор. 

По аналогии с std::thread можно заиметь такой интерфейс:

```
native_handle_type native_handle();
```

_<Примеры, где ваша идея будет полезна. Чем больше примеров и чем большую аудиторию они охватывают - тем лучше>_

Полезно для вызова низкоуровневого апи, например fsync, fdatasync. Наверняка есть еще больше юзкейсов.

_<Код c реализацией вашей идеи, если есть>_

-

Полезные ссылки:
* https://quick-bench.com/ - онлайн бенчмарк, поможет вам продемонстрировать эффективность вашего подхода
* https://godbolt.org/ - онлайн дизассемблер
* https://eel.is/c++draft/ - черновик стандарта C++ с возможностью ссылаться на конкретные параграфы
* https://wg21.link/ - универсальная ссылка на международные proposal или баги в С++, например https://wg21.link/P1000 ссылается на документ P1000, а https://wg21.link/cwg100 на 100 баг в ядре языка

**Comment by GitSparTV** [comment]
Вроде в 26 стандарте уже в черновик занесли

**Comment by KindDragon** [comment]
https://github.com/cplusplus/papers/issues/516

**Comment by apolukhin** [comment]
Как верно заметили, реализовано начиная с C++26
