### ISSUE TITLE
Добавляем недостающие type-erased перегрузки `std::format` и `std::print`

### ISSUE THREAD

**Issue by HolyBlackCat** [cpp-ru/ideas#585]
Допустим, хочется напечатать через `std::print` не напрямую в stdout/stderr/`FILE *`, а в type-erased колбек.

<details>

<summary>Пример печати в колбек</summary>

```сpp
#include <cstdio>
#include <functional>
#include <print>
#include <utility>

struct Printer
{
    using callback_t = std::function<void(std::string_view fmt, std::format_args args)>;
    callback_t callback;

    template <class ...Args>
    void print(std::format_string<Args...> fmt, Args &&...args)
    {
        callback(fmt.get(), std::make_format_args(args...));
    }

    Printer(callback_t callback) : callback(std::move(callback)) {}

    Printer(FILE *file)
        : Printer([file](std::string_view fmt, std::format_args args)
        {
            std::vprint_unicode(file, fmt, args);
        })
    {}
};

int main()
{
    Printer p(stdout);
    p.print("Hello, {}!", "World");
}
```
</details>

В теории это должно быть просто, по аналогии с `std::vprintf`, но на практике вылезает сырость API:

* При переходе с `std::print` на `std::vprint`, я должен руками выбирать между `std::vprint_unicode` и `std::vprint_nonunicode`.
* И наоборот, если мне не нужно type erasure, я не могу принудительно выбрать unicode или его отсутствие, нет `std::print_[non]unicode`.

* Нет `std::vprintln`. Вроде мелочь, но как удобно дописать `\n` непонятно. Либо копировать строку формата в `std::string` чтобы дописать `\n`, либо дергать `std::fputc('\n', file)` - и то и то странно.

* В качестве бонуса, нет  `std::vformat_to_n`, есть только `std::vformat_to`. Хотя `std::format_to_n` есть.

Как это чинить?

* Добавить `std::vformat_to_n` - тут все просто.

* Про `std::vprint` я не совсем уверен. Можно просто добавить `std::vprint` и `std::print_[non]unicode`, а с отсутствием `vprintln` ничего не делать, потому что в  libfmt он все равно [реализован через временный буфер](https://github.com/fmtlib/fmt/blob/5d55375a8a6aabf39528bdf48f7b3ded5ef4e9bb/include/fmt/core.h#L2932C48-L2932C48).

**Comment by kelbon** [comment]
Вроде мелочь, но как удобно дописать \n непонятно.
макросом, 
```cpp
#define $vprintln(fmt_string, ... /* args */) ::std::vprint(fmt_string "\n", __VA_ARGS__)
```
лучше кажется нельзя, просто потому что consteval конструктор и всякое такое
