### ISSUE TITLE
__int128_t

### ISSUE THREAD

**Issue by TheLazyProdigy** [cpp-ru/ideas#586]
Здравствуйте, я пишу обычный код на с++ с типом __int128_t, но у меня возникает проблема при вводе,выводе.
Вот мой код:
#include <bits/stdc++.h>
using namespace std;

int main() {
    ios_base::sync_with_stdio(0);
    __int128_t n,result;
    cin >> n;
    result=pow(5,n);
    cout<<result;
}

**Comment by xiran56** [comment]
Код, кстати, не "обычный", а непереносимый. Это неприемлемо для обращения к стандарту. Это вообще никак с ним не связано. Почему? **__int128_t - не тип языка, это расширение компилятора.** Возможные причины почему не работает: нет перегрузки для `std::cin`, `std::cout` и `std::pow`, и быть не должно. Напишите свои перегрузки. В общем не стреляйте пушкой по мухам, вы все равно в них не попадете. Т.е. это вообще решается с вашей стороны вашем же кодом. Нужно сначала эти типы в стандарт ввести, но, могу предположить, если бы это было возможно, это бы давно кто-то уже сделал.

**Comment by apolukhin** [comment]
В стандарт C добавили _BitInt. Надеюсь что в ближайшее время этот тип данных попадёт и в C++, вместе чо всеми нужными расширениями для стандартной библиотеки

**Comment by apolukhin** [comment]
Закрываю как дубликат для https://github.com/cpp-ru/ideas/issues/572
