### ISSUE TITLE
linalg в C++26.

### ISSUE THREAD

**Issue by Gigachader007** [cpp-ru/ideas#587]
Требую добавить полностью библиотеку glm в стандартную библиотеку.

Данное решение позволит заниматься обычной линейной алгеброй, при этом не приспосабливаться к новой стандартной реализации линейной алгебры (linalg), а использовать уже привычную библиотеку glm со всеми вещами.

Полезные ссылки:
* https://github.com/g-truc/glm - GLM

**Comment by incoder1** [comment]
Ну Boost BLAS еще понятно, но GLM o_O Может тогда и Vulkan заодно добавить в стандартную библиотеку ? 

Кстати пока не было предложений стандартизировать OpenMP хотя все известные компиляторы его поддерживают. Разные BLAS, GLM и прочие тензорные библиотеки как правило умеют его использовать.

**Comment by apolukhin** [comment]
Приняли в C++26 в https://wg21.link/P1673

Скоро напишем пост про это на Хабр
