### ISSUE TITLE
lexical_cast

### ISSUE THREAD

**Issue by Neargye** [cpp-ru/ideas#60]
_Перенос предложения:_ голоса +1, -6
_Автор идеи:_ **Damond Loks**

**Comment by Neargye** [comment]
**valera_ee 21 июля 2020, 8:58**
Хорошая библиотека, поддерживаю, но хочется, чтобы она в stl работала быстрее, чем в boost.

**yndx-antoshkka 21 июля 2020, 9:45*
Есть аналогичное предложение https://stdcpp.ru/proposals/a270e3f8-3b35-4485-8e08-2ae56afdb1c3

**Comment by apolukhin** [comment]
Закрыто в пользу #59
