### ISSUE TITLE
Добавить функцию subelements в STL контейнеры

### ISSUE THREAD

**Issue by Neargye** [cpp-ru/ideas#77]
_Перенос предложения:_ голоса +1, -4
_Автор идеи:_ **digitalEugene**

Добавить в стандартные контейнеры вроде std::vector и std::list функцию subelements, которая будет аналогом std::string::substr.

**Comment by Neargye** [comment]
**Georgy Firsov 4 марта 2020, 23:12**
Можно использовать итераторы для этой цели.

В векторе и списке итераторы соответствуют требованию InputIterator, а значит к ним можно применить std::advance (со сдвигом на положительное значение). В итоге получением итератора на первый элемент подпоследовательности и заданием длины этой подпоследовательности в сущности получаем аналог substr для std::vector, std::list, std::forward_list


** Aracks 1 мая 2020, 11:31**
Я так понимаю, что Вы пытаетесь добавить функционал на подобие, как в питоне, который позволяет оперировать произвольными подсписками списков. Только боюсь, что для стандартных STL-контейнеров это не подойдёт, ибо простые задачи, как уже сказал Georgy Firsov, легко решаются итераторами, а какие-то сложные манипуляции с подсписками попросту будут неэфффективно работать на стандартных STL-коллекциях. 

Вот если бы в STL были бы мета-коллекции, которые не хранят элементы на самом деле, а лишь представляются коллекциями, то такой функционал был бы для них полезен. Только вот такие мета-коллекции - это, скорее, функционал для СУБД и нужен-ли он в C++ сообще?

**Comment by apolukhin** [comment]
C++20 Ranges добавляют необходимый функционал:
```cpp
auto sub = container | std::views::drop(3) | std::views::take(5);
auto sub1 = std::views::counted(container.begin() + 3, 5); // assert contqiner.size() >= 3
auto sub2 = std::ranges::subrange(container.begin() + 3, container.begin() + 8); // assert contqiner.size() >= 8
```
